version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "babel-cloud-internauta-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16e75mgfgn2rx"
s3_prefix = "internauta-dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "ProjectName=babel-cloud",
    "ComponentName=internauta",
    "Environment=dev",
    "ImageVersion=__ImageVersion__"
]
image_repositories = []
tags = [
    "project=babel",
    "component=internauta",
    "env=dev"
]