AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

#TODO:
# TENIAMO TUTTO SOTTO SECRET? LE VARIABILI POSSIAMO METTERLE COME PARAMETRI E USARE I SECRETS SOLO SE RICHIESTO?
# QUI LA GESTIONE VA RIVISTA GLOBALMENTE, CREO NUOVO SECRET IN BASE-STACK? PARAMETRI? METTIAMO TUTTO IN SECRET/PARAMS E NULLA DI "CABLATO QUI?"
# -

Parameters:
  ProjectName:
    Type: String
  ComponentName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
  ImageVersion:
    Type: String

Mappings:
  #TODO: Abilita CloudMap "ilbianconero.local" per risparmiare traffico verso esterno
  Settings:
    global:
      ContainerPort: 80
      ServicePriority: 100
  Autoscaling:
    dev:
      MinCapacity: 1
      MaxCapacity: 1
    staging:
      MinCapacity: 1
      MaxCapacity: 1
    prod:
      MinCapacity: 1
      MaxCapacity: 1
  Security:
    dev:
      SecretId: babel/components-data-dev-SdIzbs
    staging:
      SecretId: babel/components-data-staging-Nw9mWq
    prod:
      SecretId: babel/components-data-... #TODO

# Metadata:

Conditions:
  IsPreProd: !Equals [!Ref Environment, preprod]
  IsProd: !Equals [!Ref Environment, prod]
  EnableAutoscaling:
    !Not [
      !Equals [
        !FindInMap [Autoscaling, !Ref Environment, MinCapacity],
        !FindInMap [Autoscaling, !Ref Environment, MaxCapacity],
      ],
    ]

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "internauta_service-${Environment}"
      # Cpu: 512 #TODO
      # Memory: 512 #TODO
      TaskRoleArn: !Ref TaskRole
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      # Volumes: []
      # RequiresCompatibilities:
      ContainerDefinitions:
        - Name: app
          #106051683257.dkr.ecr.eu-central-1.amazonaws.com/cm-media-prod-php:latest
          Image: !Sub
            - "${RepoURI}:${ImageVersion}"
            - RepoURI:
                Fn::ImportValue: !Sub "babel-infrastructure-${Environment}-internauta-repo-uri"
          Essential: true
          PortMappings: []
          #Cpu: 10
          #Memory: 256
          MemoryReservation: 480
          Environment:
            - Name: SPRING_DATASOURCE_URL
              Value: #TODO
            ###
            - Name: nextsdr_request_default_azienda-path
              Value: #TODO
            - Name: internauta_cache_redis_host
              Value: #TODO
            - Name: intimus_redis_host
              Value: #TODO
            - Name: shared_data_redis_host
              Value: #TODO
            - Name: masterjobs_redis_host
              Value: #TODO
          Secrets:
            #arn:aws:secretsmanager:region:aws_account_id:secret:secret-name:json-key:version-stage:version-id
            - Name: "SPRING_DATASOURCE_USERNAME"
              ValueFrom: !Sub
                - "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretId}:app_secret::"
                - SecretId: !FindInMap [Security, !Ref Environment, SecretId]
            - Name: "SPRING_DATASOURCE_PASSWORD"
              ValueFrom: !Sub
                - "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretId}:db_app_mysql_user::"
                - SecretId: !FindInMap [Security, !Ref Environment, SecretId]
          # MountPoints: []
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TaskLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: internauta

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - AppLBListenerRule
    Properties:
      # ServiceName: !Ref ComponentName
      Cluster:
        Fn::ImportValue: !Sub "${BaseStack}-${Environment}-ecs-cluster-arn"
      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref ComponentTG
      # Role: !Ref ServiceRole
      TaskDefinition: !Ref TaskDefinition
      HealthCheckGracePeriodSeconds: 10
      # LaunchType: FARGATE
      # CapacityProviderStrategy:
      #   - CapacityProvider: !Ref CapacityProvider
      #     Base: 1
      #     Weight: 1
      # PlacementConstraints:
      #   - PlacementConstraint
      # PlacementStrategies:
      #   - PlacementStrategy
      # PlatformVersion: String
      PropagateTags: SERVICE
      DeploymentController:
        Type: ECS # CODE_DEPLOY | ECS | EXTERNAL
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: !If [IsProd, true, false]
          Rollback: true
        MaximumPercent: 200
        MinimumHealthyPercent: 100

  ComponentTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 60
      HealthCheckPath: "/_status"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 2
      Port: !Ref ContainerPort
      Protocol: HTTP
      UnhealthyThresholdCount: 3
      VpcId:
        Fn::ImportValue: !Sub "${BaseStack}-${Environment}-vpc-id"
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"

  AppLBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ComponentTG
      Conditions:
        - Field: host-header
          Values:
            - !Sub "${EndpointId}.${HostedZone}"
      ListenerArn:
        Fn::ImportValue: !Sub "${BaseStack}-${Environment}-alb-https-listener-arn"
      Priority: !Ref ServicePriority

  TaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/${ProjectName}/${Environment}/${ComponentName}"
      RetentionInDays: 30

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}_${ComponentName}_${Environment}_task-role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:PutMetricData"
                  - "ecs:DescribeTasks"
                Resource: "*"

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}_${ComponentName}_${Environment}_execution-role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "kms:Decrypt"
                Resource: "*"
